#!/usr/bin/env node
/**
 * Install pre-commit hook vào .git/hooks/pre-commit.
 *
 * Usage:  node scripts/install-hooks.mjs
 *
 * - Sẽ KHÔNG ghi đè hook có sẵn mà không hỏi.
 * - Dùng `git config core.hooksPath .githooks` để quản lý hooks qua git thay vì
 *   sửa trực tiếp .git/hooks (dễ revert, dễ review).
 */

import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const HOOKS_DIR = join(ROOT, '.githooks');
const PRE_COMMIT = join(HOOKS_DIR, 'pre-commit');

mkdirSync(HOOKS_DIR, { recursive: true });

// Tạo pre-commit hook (gọi script scanner)
writeFileSync(
  PRE_COMMIT,
  `#!/usr/bin/env node
// Auto-generated by scripts/install-hooks.mjs
// Quét secret trong staged files trước khi commit.
import { spawnSync } from 'node:child_process';
const result = spawnSync('node', ['scripts/pre-commit.mjs'], {
  stdio: 'inherit',
  cwd: ${JSON.stringify(ROOT)},
});
process.exit(result.status ?? 1);
`,
  { mode: 0o755 }
);

console.log('✅ Pre-commit hook written to .githooks/pre-commit');

// Cấu hình git dùng .githooks thay vì .git/hooks
try {
  execSync('git config core.hooksPath .githooks', { stdio: 'inherit', cwd: ROOT });
  console.log('✅ git config core.hooksPath = .githooks');
} catch (err) {
  console.warn('⚠️  Không set được core.hooksPath (có thể sandbox chặn).');
  console.warn('   Hãy chạy thủ công khi đã ở local:');
  console.warn('   cd ' + ROOT + ' && git config core.hooksPath .githooks');
}

// Verify (best-effort, ignore error nếu không đọc được config)
try {
  const verifyOut = execSync('git config core.hooksPath', { encoding: 'utf8', cwd: ROOT }).trim();
  if (verifyOut === '.githooks') {
    console.log('\n🎉 Hook installed. Mọi `git commit` sẽ tự động scan secret.');
    console.log('   Để bypass (không khuyến nghị):  git commit --no-verify');
    console.log('   Để cài gitleaks (rule phong phú hơn):  brew install gitleaks');
  } else {
    console.warn(`\n⚠️  core.hooksPath = ${verifyOut} (expected '.githooks')`);
  }
} catch {
  console.warn('\n⚠️  Không đọc được git config để verify. Hook file đã có tại .githooks/pre-commit');
  console.warn('   Khi về local, chạy: git config core.hooksPath .githooks');
}
